### ISSUE TITLE
SPSA doc string out of date

### ISSUE THREAD

**Issue by Durd3nT** [qiskit-community/qiskit-algorithms#106]
### Environment

- **Qiskit Algorithms version**: 0.2.1
- **Python version**:
- **Operating system**:

### What is happening?

The small code examples in the doc string of [qiskit_algorithms/optimizers/spsa.py](https://qiskit.org/ecosystem/algorithms/stubs/qiskit_algorithms.optimizers.SPSA.html#spsa) still show the old signature of optimizers in qiskit instead of the new scipy-style optimizers. This includes a method `optimize` that is now called `minimize`, returning `point, value, niter` instead of `OptimizationResult` objects, etc.

### How can we reproduce the issue?

--

### What should happen?

The code examples shout show the new way of using optimizers in qiskit.

**Comment by woodsp-ibm** [comment]
Thanks for noticing and raising this issue. It is also using StateFn which was part of `qiskit.opflow` which was deprecated and will no longer be present in the upcoming Qiskit 1.0. The first part could be re-done showing it used with an Estimator. Though I do not know how much value there is in that given its usage is no different syntactically than any other optimizer in that regard.
