### ISSUE TITLE
PrimitiveJob.submit() is deprecated as of qiskit 0.46.0

### ISSUE THREAD

**Issue by woodsp-ibm** [qiskit-community/qiskit-algorithms#126]
`AlgorithmJob`, used by gradients and fidelities, extends Qiskit's PrimitiveJob. PrimitiveJob has been changed to no longer extend JobV1 and at the same time `submit()` was deprecated. The CI jobs against 1.0.0 are now logging the following so code needs updating accordingly.

> ``qiskit.primitives.primitive_job.PrimitiveJob.submit()`` is deprecated as of qiskit 0.46.0. It will be removed no earlier than 3 months after the release date

**Comment by ElePT** [comment]
It might make sense to make `AlgorithmJob` extend `JobV1` directly, I feel like `PrimitiveJob` is diverging from what we particularly need here.
