### ISSUE TITLE
IAE: `inverse()` not implemented for reset

### ISSUE THREAD

**Issue by sirgeorgesawcon** [qiskit-community/qiskit-algorithms#72]
### Environment

- **Qiskit Algorithms version**:  0.2.0
- **Python version**:3.10.12
- **Operating system**:Linux

### What is happening?

While Implementing an IAE routine, when I reset some qubits to |0> using `circuit.reset`, the following error is shown:

`CircuitError: 'inverse() not implemented for reset.'`

### How can we reproduce the issue?

Make a simple circuit just for testing:

```
from qiskit import QuantumRegister, ClassicalRegister
from qiskit import QuantumCircuit, execute
from qiskit.circuit.library import IntegerComparator
from qiskit import Aer


backend = Aer.get_backend('aer_simulator')

q = QuantumRegister(9,'q')


circuit = QuantumCircuit(q)

a = 3

comparator = IntegerComparator(num_state_qubits=3, value=a, geq=True)



circuit = circuit.compose(comparator,qubits=[0,1,2,3,7,8])


circuit.reset([3, 4, 5])



```
The Quantum circuit looks like this:

![output](https://github.com/qiskit-community/qiskit-algorithms/assets/63145298/31c19100-b8aa-4cf5-8df2-a1e5de97592f)

Then simply run the IAE

```

epsilon = 0.01   # the error
alpha = 0.5      # the alpha value
num_shots = 5000

problem = EstimationProblem(state_preparation=circuit,objective_qubits=[8])     # the quantum circuit

# construct amplitude estimation
iae = IterativeAmplitudeEstimation(
    epsilon_target=epsilon,
    alpha=alpha,
    sampler=Sampler(run_options={"shots": num_shots})
)
```

and

```
result = iae.estimate(problem)
print(result)
```

### What should happen?

It should print out IAE result.

### Any suggestions?

It has something to do with the `reset` function, and IAE compatibility with it.

**Comment by Cryoris** [comment]
That's because the Grover operator in amplitude estimation contains the inverse of the state preparation. In your case, this is the integer comparator plus the resets, which cannot be inverted. Do you need the resets, if they act on qubits that are not part of the objective? If yes, you could circumvent this issue by constructing the Grover operator for your problem manually.
