### ISSUE TITLE
Migrate release notes?

### ISSUE THREAD

**Issue by ElePT** [qiskit-community/qiskit-algorithms#8]
How to proceed about the algorithm-related qiskit-terra releasenotes?

TODO/to be discussed

**Comment by woodsp-ibm** [comment]
Seems like this would be awkward given that it will be a new 0.1.0 release. There are notes talking about deprecation etc., stuff being removed that is no longer relevant. If we wanted to do something, and we should most likely have a release note for 0.1.0 that possibly outlines the transition in a prelude, that could just point over to Qiskit release notes and state the past release history is there.

**Comment by Eric-Arellano** [comment]
+1. I think we could close this one as "not planned"

**Comment by ElePT** [comment]
Not planned
